services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/cert/vdzundza.online.pem:/cert/vdzundza.online.pem
      - ~/cert/vdzundza.online.key:/cert/vdzundza.online.key
      - ./:/etc/traefik

networks:
  default:
    external:
      name: traefik
