global:
  checkNewVersion: true
  sendAnonymousUsage: true
  middlewares:
    www-remover:
      redirectregex:
        regex: ^https://www\.(.*)
        replacement: https://$1
    auth:
      basicAuth:
        users:
          - "user:$$2y$$05$$vIgAvVVmUzModrQcTEtdTekgjeJp/guBKsKyh8fE4/TYLzyt02IiC"

  routers:
    www-router:
      rule: HostRegexp(`{host:www\..+}`)
      tls: true
      service: noop@internal
      middlewares: www-remover

    dashboard:
      rule: Host(`traefik.vdzundza.online`) || (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
      middlewares:
        - auth

tls:
  options:
    default:
      sniStrict: true
  certificates:
    - certFile: /cert/vdzundza.online.pem
      keyFile: /cert/vdzundza.online.key
