log:
  level: DEBUG

providers:
  docker: true
  file:
    filename: /etc/traefik/dynamic_conf.yml

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: vdzundza@protonmail.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
